//! tree-sitter-rust (0.24) backed extractor.
//!
//! Node kinds below were confirmed against a real parse of a representative
//! sample with this exact grammar version (via `tree.root_node().to_sexp()`
//! and a full node-kind/field walk) rather than recalled from memory — see
//! the extraction rules in docs/ARCHITECTURE.md "Adding a language".
//!
//! Known limitations (documented, not silent gaps):
//! - Items produced by macro expansion (`macro_rules!`-defined items, or
//!   items generated by invoking a macro) are not extracted — tree-sitter
//!   parses macro bodies as opaque token trees, so this would require macro
//!   expansion, out of scope for a syntax-only extractor.
//! - Tuple-struct/enum-variant construction calls (e.g. `Foo(1, 2)`) are
//!   indistinguishable from ordinary function calls without type
//!   information, so they're recorded as `Call` references rather than
//!   `Instantiation`. Only brace-literal `struct_expression` (`Foo { .. }`)
//!   is recorded as `Instantiation`.

use crate::languages::support::{
    collect_kind_texts, collect_warnings, node_text, preceding_doc_comments,
    signature_before_field, span_of,
};
use crate::{
    ImportEdge, LanguageExtractor, ParseError, ParseResult, ParsedReference, ParsedSymbol,
};
use engine_core::{Language, ReferenceKind, RepoPath, SymbolKind};
use tree_sitter::{Node, Parser};

pub struct RustExtractor;

impl LanguageExtractor for RustExtractor {
    fn language(&self) -> Language {
        Language::Rust
    }

    fn extract(&self, source: &str, file: &RepoPath) -> Result<ParseResult, ParseError> {
        let mut parser = Parser::new();
        parser
            .set_language(&tree_sitter_rust::LANGUAGE.into())
            .map_err(|_| ParseError::TreeSitterFailure { file: file.clone() })?;
        let tree = parser
            .parse(source, None)
            .ok_or_else(|| ParseError::TreeSitterFailure { file: file.clone() })?;
        let root = tree.root_node();

        let mut result = ParseResult {
            warnings: collect_warnings(root),
            ..Default::default()
        };

        walk_items(root, source, None, false, &mut result);
        walk_refs(root, source, &mut result.references);

        Ok(result)
    }
}

fn qualify(qualifier: Option<&str>, name: &str) -> String {
    match qualifier {
        Some(q) if !q.is_empty() => format!("{q}::{name}"),
        _ => name.to_string(),
    }
}

/// Whether `node` has a `pub` (or `pub(...)`) modifier as its first named
/// child — the shape tree-sitter-rust gives every visibility-qualifiable
/// item (functions, structs, enums, consts, type aliases, mods, fields).
fn has_pub_modifier(node: Node) -> bool {
    node.named_child(0)
        .map(|c| c.kind() == "visibility_modifier")
        .unwrap_or(false)
}

fn is_doc_comment(node: Node) -> bool {
    matches!(node.kind(), "line_comment" | "block_comment")
        && node.child_by_field_name("doc").is_some()
}

fn doc_comment_for<'a>(node: Node<'a>, source: &'a str) -> Option<String> {
    let comments = preceding_doc_comments(node, is_doc_comment);
    if comments.is_empty() {
        return None;
    }
    let lines: Vec<String> = comments
        .into_iter()
        .map(|c| {
            c.child_by_field_name("doc")
                .map(|d| node_text(d, source).trim_end().to_string())
                .unwrap_or_default()
        })
        .collect();
    let joined = lines.join("\n").trim().to_string();
    if joined.is_empty() {
        None
    } else {
        Some(joined)
    }
}

fn field_name_text<'a>(node: Node<'a>, field: &str, source: &'a str) -> Option<&'a str> {
    node.child_by_field_name(field)
        .map(|n| node_text(n, source))
}

/// Push a `TypeUsage` reference for every `type_identifier` found within
/// `type_node`'s subtree (covers wrapped forms like `&Foo`, `Vec<Foo>`,
/// `Option<Foo>`).
fn push_type_usages(
    type_node: Node,
    source: &str,
    from_symbol: Option<&str>,
    refs: &mut Vec<ParsedReference>,
) {
    for name in collect_kind_texts(type_node, "type_identifier", source) {
        refs.push(ParsedReference {
            from_span: span_of(type_node),
            from_symbol_name: from_symbol.map(|s| s.to_string()),
            to_name: name.to_string(),
            kind: ReferenceKind::TypeUsage,
        });
    }
}

fn push_signature_type_usages(
    fn_node: Node,
    source: &str,
    name: &str,
    refs: &mut Vec<ParsedReference>,
) {
    if let Some(params) = fn_node.child_by_field_name("parameters") {
        push_type_usages(params, source, Some(name), refs);
    }
    if let Some(ret) = fn_node.child_by_field_name("return_type") {
        push_type_usages(ret, source, Some(name), refs);
    }
}

/// Driver: `mod`/`impl`/`trait` bodies can nest arbitrarily deeply
/// (`mod a { mod a { mod a { ... } } }`), and tree-sitter parses that fine —
/// so the per-container work below runs off an explicit queue rather than
/// recursing, exactly like `walk_refs`, to avoid a native stack overflow on
/// adversarial input. See `walk_refs`'s doc comment for the full rationale.
fn walk_items(
    container: Node,
    source: &str,
    qualifier: Option<&str>,
    container_exported: bool,
    out: &mut ParseResult,
) {
    let mut queue: Vec<(Node, Option<String>, bool)> =
        vec![(container, qualifier.map(str::to_string), container_exported)];
    while let Some((container, qualifier, container_exported)) = queue.pop() {
        walk_items_one_level(
            container,
            source,
            qualifier.as_deref(),
            container_exported,
            out,
            &mut queue,
        );
    }
}

#[allow(clippy::too_many_lines)]
fn walk_items_one_level<'a>(
    container: Node<'a>,
    source: &str,
    qualifier: Option<&str>,
    container_exported: bool,
    out: &mut ParseResult,
    queue: &mut Vec<(Node<'a>, Option<String>, bool)>,
) {
    let mut cursor = container.walk();
    let children: Vec<Node> = container.named_children(&mut cursor).collect();
    for child in children {
        match child.kind() {
            "function_item" => {
                let Some(name) = field_name_text(child, "name", source) else {
                    continue;
                };
                let name = name.to_string();
                // A `pub fn` inside an `impl` block is exported regardless of
                // the impl's own visibility; an unqualified `fn` inherits the
                // enclosing container's exported-ness (relevant for trait
                // default-method bodies, which never carry their own `pub`).
                let exported = if has_pub_modifier(child) {
                    true
                } else {
                    container_exported
                };
                let kind = if qualifier.is_some() {
                    SymbolKind::Method
                } else {
                    SymbolKind::Function
                };
                out.symbols.push(ParsedSymbol {
                    name: name.clone(),
                    qualified_name: qualify(qualifier, &name),
                    kind,
                    span: span_of(child),
                    is_exported: exported,
                    doc_comment: doc_comment_for(child, source),
                    signature: Some(signature_before_field(child, source, &["body"])),
                });
                push_signature_type_usages(child, source, &name, &mut out.references);
            }
            "function_signature_item" => {
                // Trait method declarations without a body (e.g. `fn area(&self) -> f64;`).
                let Some(name) = field_name_text(child, "name", source) else {
                    continue;
                };
                let name = name.to_string();
                out.symbols.push(ParsedSymbol {
                    name: name.clone(),
                    qualified_name: qualify(qualifier, &name),
                    kind: SymbolKind::Method,
                    span: span_of(child),
                    is_exported: container_exported,
                    doc_comment: doc_comment_for(child, source),
                    signature: Some(signature_before_field(child, source, &["body"])),
                });
                push_signature_type_usages(child, source, &name, &mut out.references);
            }
            "struct_item" => {
                let Some(name) = field_name_text(child, "name", source) else {
                    continue;
                };
                out.symbols.push(ParsedSymbol {
                    name: name.to_string(),
                    qualified_name: qualify(qualifier, name),
                    kind: SymbolKind::Struct,
                    span: span_of(child),
                    is_exported: has_pub_modifier(child),
                    doc_comment: doc_comment_for(child, source),
                    signature: Some(signature_before_field(child, source, &["body"])),
                });
                if let Some(body) = child.child_by_field_name("body") {
                    push_type_usages(body, source, Some(name), &mut out.references);
                }
            }
            "trait_item" => {
                let Some(name) = field_name_text(child, "name", source) else {
                    continue;
                };
                let name = name.to_string();
                let exported = has_pub_modifier(child);
                out.symbols.push(ParsedSymbol {
                    name: name.clone(),
                    qualified_name: qualify(qualifier, &name),
                    kind: SymbolKind::Trait,
                    span: span_of(child),
                    is_exported: exported,
                    doc_comment: doc_comment_for(child, source),
                    signature: Some(signature_before_field(child, source, &["body"])),
                });
                if let Some(body) = child.child_by_field_name("body") {
                    queue.push((body, Some(qualify(qualifier, &name)), exported));
                }
            }
            "impl_item" => {
                let Some(type_name) = field_name_text(child, "type", source) else {
                    continue;
                };
                let type_name = type_name.to_string();
                let is_trait_impl = child.child_by_field_name("trait").is_some();
                if let Some(trait_name) = field_name_text(child, "trait", source) {
                    out.references.push(ParsedReference {
                        from_span: span_of(child),
                        from_symbol_name: None,
                        to_name: trait_name.to_string(),
                        kind: ReferenceKind::Implements,
                    });
                }
                if let Some(body) = child.child_by_field_name("body") {
                    // Trait-impl methods never carry their own `pub` — Rust
                    // exports them precisely when the trait (and type) are
                    // visible, which we approximate as "yes" since we can't
                    // see the trait's definition from a single-file parse.
                    // Inherent-impl methods (no `trait` field) always need
                    // their own explicit `pub`.
                    queue.push((body, Some(qualify(qualifier, &type_name)), is_trait_impl));
                }
            }
            "enum_item" => {
                let Some(name) = field_name_text(child, "name", source) else {
                    continue;
                };
                out.symbols.push(ParsedSymbol {
                    name: name.to_string(),
                    qualified_name: qualify(qualifier, name),
                    kind: SymbolKind::Enum,
                    span: span_of(child),
                    is_exported: has_pub_modifier(child),
                    doc_comment: doc_comment_for(child, source),
                    signature: Some(signature_before_field(child, source, &["body"])),
                });
            }
            "const_item" | "static_item" => {
                let Some(name) = field_name_text(child, "name", source) else {
                    continue;
                };
                out.symbols.push(ParsedSymbol {
                    name: name.to_string(),
                    qualified_name: qualify(qualifier, name),
                    kind: SymbolKind::Constant,
                    span: span_of(child),
                    is_exported: has_pub_modifier(child),
                    doc_comment: doc_comment_for(child, source),
                    signature: Some(signature_before_field(child, source, &["value"])),
                });
                if let Some(ty) = child.child_by_field_name("type") {
                    push_type_usages(ty, source, None, &mut out.references);
                }
            }
            "type_item" => {
                let Some(name) = field_name_text(child, "name", source) else {
                    continue;
                };
                out.symbols.push(ParsedSymbol {
                    name: name.to_string(),
                    qualified_name: qualify(qualifier, name),
                    kind: SymbolKind::TypeAlias,
                    span: span_of(child),
                    is_exported: has_pub_modifier(child),
                    doc_comment: doc_comment_for(child, source),
                    signature: Some(signature_before_field(child, source, &[])),
                });
                if let Some(ty) = child.child_by_field_name("type") {
                    push_type_usages(ty, source, None, &mut out.references);
                }
            }
            "mod_item" => {
                let Some(name) = field_name_text(child, "name", source) else {
                    continue;
                };
                let name = name.to_string();
                let exported = has_pub_modifier(child);
                out.symbols.push(ParsedSymbol {
                    name: name.clone(),
                    qualified_name: qualify(qualifier, &name),
                    kind: SymbolKind::Module,
                    span: span_of(child),
                    is_exported: exported,
                    doc_comment: doc_comment_for(child, source),
                    signature: Some(signature_before_field(child, source, &["body"])),
                });
                if let Some(body) = child.child_by_field_name("body") {
                    // A module's own `pub` controls whether the module is
                    // importable, not whether items inside it are exported —
                    // each item still needs its own `pub`.
                    queue.push((body, Some(qualify(qualifier, &name)), false));
                }
            }
            "use_declaration" => extract_use(child, source, &mut out.imports),
            _ => {}
        }
    }
}

/// Split a `use`-tree leaf path into (everything before the last `::`
/// segment, if any, exactly as written; the last segment itself). A bare
/// `identifier`/`self`/`crate`/`super` leaf has no leading part.
fn split_leaf_path<'a>(path_node: Node<'a>, source: &'a str) -> (Option<&'a str>, &'a str) {
    match path_node.kind() {
        "scoped_identifier" => {
            let leading = path_node
                .child_by_field_name("path")
                .map(|p| node_text(p, source));
            let name = field_name_text(path_node, "name", source).unwrap_or("");
            (leading, name)
        }
        _ => (None, node_text(path_node, source)),
    }
}

/// The `source_module` for a leaf import: the enclosing group's shared
/// prefix combined with the leaf's own leading path segment, falling back
/// to whichever of those two pieces is actually present, and finally to the
/// leaf's own name when there's no module distinct from it at all (`use
/// foo;` binds `foo` with no separate "module `foo` comes from").
fn module_for(prefix: Option<&str>, leading: Option<&str>, name: &str) -> String {
    match (prefix, leading) {
        (Some(p), Some(l)) => format!("{p}::{l}"),
        (Some(p), None) => p.to_string(),
        (None, Some(l)) => l.to_string(),
        (None, None) => name.to_string(),
    }
}

fn extract_use(decl: Node, source: &str, imports: &mut Vec<ImportEdge>) {
    let Some(argument) = decl.child_by_field_name("argument") else {
        return;
    };
    let span = span_of(decl);
    extract_use_tree(argument, None, source, span, imports);
}

/// Iterative (explicit-stack) traversal — `use a::{b::{c::{...}}}` groups
/// can nest arbitrarily deeply in adversarial input; see `walk_refs`'s doc
/// comment for the stack-overflow rationale this avoids.
fn extract_use_tree(
    node: Node,
    prefix: Option<String>,
    source: &str,
    span: engine_core::Span,
    imports: &mut Vec<ImportEdge>,
) {
    let mut stack: Vec<(Node, Option<String>)> = vec![(node, prefix)];
    while let Some((node, prefix)) = stack.pop() {
        match node.kind() {
            "identifier" | "self" | "crate" | "super" => {
                let name = node_text(node, source).to_string();
                // A bare leaf with no enclosing `{...}` group has no separate
                // "module it's imported from" distinct from itself (`use foo;`
                // binds `foo`) — the module IS the name in that case.
                let module = prefix.clone().unwrap_or_else(|| name.clone());
                imports.push(ImportEdge {
                    local_name: name.clone(),
                    source_module: module,
                    imported_name: name,
                    span,
                });
            }
            "scoped_identifier" => {
                let (leading, name) = split_leaf_path(node, source);
                let module = module_for(prefix.as_deref(), leading, name);
                imports.push(ImportEdge {
                    local_name: name.to_string(),
                    source_module: module,
                    imported_name: name.to_string(),
                    span,
                });
            }
            "use_as_clause" => {
                let Some(path) = node.child_by_field_name("path") else {
                    continue;
                };
                let alias = field_name_text(node, "alias", source)
                    .unwrap_or("")
                    .to_string();
                let (leading, name) = split_leaf_path(path, source);
                let module = module_for(prefix.as_deref(), leading, name);
                imports.push(ImportEdge {
                    local_name: alias,
                    source_module: module,
                    imported_name: name.to_string(),
                    span,
                });
            }
            "scoped_use_list" => {
                let Some(path) = node.child_by_field_name("path") else {
                    continue;
                };
                let path_text = node_text(path, source).to_string();
                let new_prefix = match &prefix {
                    Some(p) => format!("{p}::{path_text}"),
                    None => path_text,
                };
                if let Some(list) = node.child_by_field_name("list") {
                    let mut cursor = list.walk();
                    let items: Vec<Node> = list.named_children(&mut cursor).collect();
                    for item in items.into_iter().rev() {
                        stack.push((item, Some(new_prefix.clone())));
                    }
                }
            }
            "use_list" => {
                let mut cursor = node.walk();
                let items: Vec<Node> = node.named_children(&mut cursor).collect();
                for item in items.into_iter().rev() {
                    stack.push((item, prefix.clone()));
                }
            }
            // `use foo::*;` — no concrete local binding to record.
            "use_wildcard" => {}
            _ => {}
        }
    }
}

fn call_target<'a>(function_node: Node<'a>, source: &'a str) -> &'a str {
    match function_node.kind() {
        "field_expression" => field_name_text(function_node, "field", source).unwrap_or(""),
        "scoped_identifier" => field_name_text(function_node, "name", source).unwrap_or(""),
        _ => node_text(function_node, source),
    }
}

/// Iterative (explicit-stack) traversal — deliberately not natural
/// recursion. A malicious source file can nest expressions arbitrarily
/// deeply (e.g. hundreds of thousands of parenthesized calls); tree-sitter
/// itself parses that fine, but a recursive-descent walk over the resulting
/// tree would blow the native call stack and abort the whole process, which
/// is an unrecoverable crash rather than a graceful per-file parse error —
/// exactly the adversarial-content DoS this engine's threat model rules
/// out. See the sibling `walk_refs` in `python.rs`/`go.rs`/`ts_js_common.rs`
/// for the same fix.
fn walk_refs(root: Node, source: &str, refs: &mut Vec<ParsedReference>) {
    let mut stack: Vec<(Node, Option<String>)> = vec![(root, None)];
    while let Some((node, current)) = stack.pop() {
        let next_current: Option<String> = match node.kind() {
            "function_item" | "function_signature_item" => {
                field_name_text(node, "name", source).map(|s| s.to_string())
            }
            _ => current,
        };

        match node.kind() {
            "call_expression" => {
                if let Some(func) = node.child_by_field_name("function") {
                    refs.push(ParsedReference {
                        from_span: span_of(node),
                        from_symbol_name: next_current.clone(),
                        to_name: call_target(func, source).to_string(),
                        kind: ReferenceKind::Call,
                    });
                }
            }
            "struct_expression" => {
                if let Some(name) = node.child_by_field_name("name") {
                    refs.push(ParsedReference {
                        from_span: span_of(node),
                        from_symbol_name: next_current.clone(),
                        to_name: node_text(name, source).to_string(),
                        kind: ReferenceKind::Instantiation,
                    });
                }
            }
            _ => {}
        }

        let mut cursor = node.walk();
        let children: Vec<Node> = node.named_children(&mut cursor).collect();
        for child in children.into_iter().rev() {
            stack.push((child, next_current.clone()));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn extract(source: &str) -> ParseResult {
        RustExtractor
            .extract(source, &RepoPath::new("test.rs"))
            .expect("parse should succeed")
    }

    #[test]
    fn extracts_a_simple_function() {
        let result = extract("pub fn helper(x: i32) -> i32 { x + 1 }");
        let sym = result.symbols.iter().find(|s| s.name == "helper").unwrap();
        assert_eq!(sym.kind, SymbolKind::Function);
        assert!(sym.is_exported);
        assert_eq!(sym.qualified_name, "helper");
        assert_eq!(
            sym.signature.as_deref(),
            Some("pub fn helper(x: i32) -> i32")
        );
    }

    #[test]
    fn private_function_is_not_exported() {
        let result = extract("fn helper() {}");
        let sym = result.symbols.iter().find(|s| s.name == "helper").unwrap();
        assert!(!sym.is_exported);
    }

    #[test]
    fn extracts_struct_with_method_and_qualified_name() {
        let source = r#"
pub struct Point { x: i32 }

impl Point {
    pub fn new() -> Self { Point { x: 0 } }
}
"#;
        let result = extract(source);
        let strct = result.symbols.iter().find(|s| s.name == "Point").unwrap();
        assert_eq!(strct.kind, SymbolKind::Struct);
        assert!(strct.is_exported);

        let method = result.symbols.iter().find(|s| s.name == "new").unwrap();
        assert_eq!(method.kind, SymbolKind::Method);
        assert_eq!(method.qualified_name, "Point::new");
    }

    #[test]
    fn extracts_doc_comment() {
        let source = "/// Does a thing.\npub fn helper() {}";
        let result = extract(source);
        let sym = result.symbols.iter().find(|s| s.name == "helper").unwrap();
        assert_eq!(sym.doc_comment.as_deref(), Some("Does a thing."));
    }

    #[test]
    fn extracts_use_declaration() {
        let result = extract("use crate::foo::{Bar, Baz as Qux};");
        assert_eq!(result.imports.len(), 2);
        let bar = result
            .imports
            .iter()
            .find(|i| i.local_name == "Bar")
            .unwrap();
        assert_eq!(bar.source_module, "crate::foo");
        assert_eq!(bar.imported_name, "Bar");
        let qux = result
            .imports
            .iter()
            .find(|i| i.local_name == "Qux")
            .unwrap();
        assert_eq!(qux.imported_name, "Baz");
        assert_eq!(qux.source_module, "crate::foo");
    }

    #[test]
    fn extracts_simple_use_path() {
        let result = extract("use std::fmt;");
        assert_eq!(result.imports.len(), 1);
        let imp = &result.imports[0];
        assert_eq!(imp.local_name, "fmt");
        assert_eq!(imp.imported_name, "fmt");
        assert_eq!(imp.source_module, "std");
    }

    #[test]
    fn extracts_call_reference_with_enclosing_symbol() {
        let source = r#"
pub fn helper(x: i32) -> i32 { x }

pub fn caller() {
    helper(1);
}
"#;
        let result = extract(source);
        let call = result
            .references
            .iter()
            .find(|r| r.kind == ReferenceKind::Call && r.to_name == "helper")
            .unwrap();
        assert_eq!(call.from_symbol_name.as_deref(), Some("caller"));
    }

    #[test]
    fn extracts_implements_reference_for_trait_impl() {
        let source = r#"
pub trait Shape { fn area(&self) -> f64; }
pub struct Point;
impl Shape for Point {
    fn area(&self) -> f64 { 0.0 }
}
"#;
        let result = extract(source);
        let implements = result
            .references
            .iter()
            .find(|r| r.kind == ReferenceKind::Implements)
            .unwrap();
        assert_eq!(implements.to_name, "Shape");
    }

    #[test]
    fn recovers_from_syntax_errors_with_warning() {
        let result = extract("pub fn broken(x: i32 -> i32 { x }\npub fn ok() {}");
        assert!(!result.warnings.is_empty());
        assert!(result.symbols.iter().any(|s| s.name == "ok"));
    }

    #[test]
    fn empty_file_yields_no_symbols() {
        let result = extract("");
        assert!(result.symbols.is_empty());
        assert!(result.warnings.is_empty());
    }

    #[test]
    fn all_comment_file_yields_no_symbols_or_warnings() {
        let result = extract("// just a comment\n// and another\n");
        assert!(result.symbols.is_empty());
        assert!(result.warnings.is_empty());
    }

    #[test]
    fn nested_module_qualifies_symbol_path() {
        let result = extract("pub mod outer {\n    pub fn inner() {}\n}\n");
        let sym = result.symbols.iter().find(|s| s.name == "inner").unwrap();
        assert_eq!(sym.qualified_name, "outer::inner");
        assert!(sym.is_exported);
    }
}
